//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgenciaPrueba.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Viaje
    {
        public int CodigodeViaje { get; set; }
        public Nullable<int> NumeroPlazas { get; set; }
        public string LugarOrigen { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public string Destino { get; set; }
    }
}
